
name: Android CI

on:
  push:
    branches:
      - main  # 或者指定你希望触发构建的其他分支

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Download Gradle dependencies
      run: ./gradlew build --no-daemon

    - name: Build APK
      run: ./gradlew assembleRelease

    # 查找生成的 APK 文件的位置
    - name: Find APK
      run: find . -name "*.apk"

    # 上传 release 版本的 APK 文件
    - name: Upload release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-unsigned.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
